name: ray-quickstart
channels:
  - defaults
  - conda-forge
  - apple
dependencies:
  - python==3.10.11
  - pip
  - pipenv
  - build
  - grpcio=1.43.0 # install conda version to get version of grpc so that Ray works on Macs
  - apple::tensorflow-deps
  - twine
  - pip:
      - ray[default]
variables:
  PIPENV_PIPFILE: Pipfile.mac
