[build-system]
requires = ['hatchling']
build-backend = 'hatchling.build'

[project]
name = 'ray-quickstart'
authors = [
    {name='Tuyen Truong', email='tuyen.truong@gmail.com'}
]
description='Starter ML project that allows you to develop on your Mac and train using your PC computer (via Ubuntu WSL)'
readme = 'README.md'
requires-python = '>=3.7'
dependencies = [
    'ray~=2.2',
]
classifiers = [
    'Development Status :: 3 - Alpha',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: MIT License',
    'Operating System :: OS Independent',
    'Programming Language :: Python :: 3',
]
dynamic = ['version']

[project.urls]
'Homepage' = 'https://github.com/tuyentruong/ray_quickstart'
'Bug Tracker' = 'https://github.com/tuyentruong/ray_quickstart/issues'

[tool]

[tool.hatch.version]
path = 'src/ray_quickstart/__about__.py'

[tool.hatch.build.targets.sdist]
exclude = [
    '/docs'
]

[tool.hatch.build.targets.wheel]
packages = ['src/ray_quickstart']
